### ISSUE TITLE
not working with mongoose 5.5.3

### ISSUE THREAD

**Issue by AlbertHambardzumyan** [meanie/mongoose-to-json#7] opened 2019-04-25 10:41 UTC
mongoose: `5.5.3`
@meanie/mongoose-to-json: `2.3.0`

Use case:
The `findOneAndUpdate` call returns:

{"__v": 0, "_id": "5c5ad0ca633de27c588a5bb1", "username": ...

FYI, works fine with mongoose: `5.5.2`

**Comment by adamreisnz** [comment] 2019-04-28 05:02
Thanks for reporting, I'll investigate and see what's happening.

**Comment by adamreisnz** [comment] 2019-04-28 07:22
Could you please clarify your problem and post a larger reproducible code example?
I am using 5.5.4 now and the following works fine:

```js
const foo = await mongoose
      .model('Foo')
      .findOneAndUpdate(...);
console.log(foo.toJSON());
```

Returns:

```json
{"id": "...."}
```

**Comment by AlbertHambardzumyan** [comment] 2019-04-29 09:33
@adamreisnz 
I have mentioned mongoose version `5.5.3`, I have no clue about `5.5.4`
The mongoose `5.5.3` was the latest version at the time I have created this issue.

Give it try with `mongoose 5.5.3`

**Comment by adamreisnz** [comment] 2019-04-29 20:32
Well, 5.5.4 was the latest at the time that I tried it, so maybe whatever the issue was has now been fixed. Since I can't reproduce it with 5.5.4 I'm going to close this issue, if you can reproduce it with 5.5.4 please post a standalone script which reproduces the issue and I'll investigate further.

**Closed as completed by adamreisnz** 2019-04-29 20:32 UTC
