### ISSUE TITLE
Doesn't work when setting up as a global plugin

### ISSUE THREAD

**Issue by apedyashev** [meanie/mongoose-to-json#5] opened 2018-03-06 14:11 UTC
Great plugin!
But all documents still have `_id` when using this example 

```
const mongoose = require('mongoose');
const toJson = require('@meanie/mongoose-to-json');

mongoose.plugin(toJson);
```

**Comment by adamreisnz** [comment] 2018-03-06 19:22
Hey there, thanks for raising this issue. The global setup works fine for me, and I use it extensively in our projects. Could you tell me what versions you are using for mongoose and @meanie/mongoose-to-json?

**Comment by apedyashev** [comment] 2018-03-09 10:15
Sorry about that. Versions:
"@meanie/mongoose-to-json": "2.2.0",
"mongoose": "5.0.7",

**Comment by adamreisnz** [comment] 2018-03-09 17:36
I can't seem to reproduce, it's working as intended;

```js
'use strict';

const mongoose = require('mongoose');
const toJSON = require('@meanie/mongoose-to-json');
const {Schema, Types: {ObjectId}} = mongoose;

mongoose.plugin(toJSON);

const FooSchema = new Schema({
  name: String,
});

const BarSchema = new Schema({
  num: Number,
});

const Foo = mongoose.model('Foo', FooSchema);
const Bar = mongoose.model('Bar', BarSchema);

const foo = new Foo({
  name: 'Test',
});
const bar = new Bar({
  num: 1,
});

console.log(foo.toJSON());
console.log(bar.toJSON());
```

Output:

```
{ name: 'Test', id: '5aa2c5bc8cb38d06f598db52' }
{ num: 1, id: '5aa2c5bc8cb38d06f598db53' }
```

Could you share more of how you create your models etc and/or create a standalone example of how it fails?

**Comment by yehuda54** [comment] 2018-11-20 19:22
I am having the same issue when trying to apply the plugin globally.  I am not sure if this is an issue, but my mongoose setup and schema model defs  are divided in multiple files.  In each model file I include:

var mongoose = require('mongoose');

I wonder if the global def is not carrying over across files

**Comment by adamreisnz** [comment] 2018-11-20 20:08
No that should be fine, the mongoose plugin is exported as a singleton so whenever you require it in a file, it will require the same module.

Could you share more of how you create your models etc and/or create a standalone example of how it fails?

**Comment by djansyle** [comment] 2018-12-27 12:45
I also experience this issue, but I was able to figure out what causes this. Setting it as a global plugin after models are being created, causes the plugin to not work.

`'use strict';

const mongoose = require('mongoose');
const toJSON = require('@meanie/mongoose-to-json');
const { Schema } = mongoose;

const FooSchema = new Schema({
  name: String,
});

const BarSchema = new Schema({
  num: Number,
});

const Foo = mongoose.model('Foo', FooSchema);
mongoose.plugin(toJSON);

const Bar = mongoose.model('Bar', BarSchema);

const foo = new Foo({
  name: 'Test',
});
const bar = new Bar({
  num: 1,
});

console.log(foo.toJSON());
console.log(bar.toJSON());
`
Output:
`{ _id: 5c24c8bb85d5b446aef2d47e, name: 'Test' }
{ num: 1, id: '5c24c8bb85d5b446aef2d47f' }`

**Comment by djansyle** [comment] 2018-12-27 12:51
I also experience this issue, but I was able to figure out what causes this. Setting it as a global plugin after models are being created, causes the plugin to not work.


```javascript
'use strict'
const mongoose = require('mongoose');
const toJSON = require('@meanie/mongoose-to-json');
const { Schema } = mongoose;

const FooSchema = new Schema({
  name: String,
});

const BarSchema = new Schema({
  num: Number,
});

const Foo = mongoose.model('Foo', FooSchema);
mongoose.plugin(toJSON);

const Bar = mongoose.model('Bar', BarSchema);

const foo = new Foo({
  name: 'Test',
});
const bar = new Bar({
  num: 1,
});

console.log(foo.toJSON());
console.log(bar.toJSON());
```

Output:

```
{ _id: 5c24c8bb85d5b446aef2d47e, name: 'Test' }
{ num: 1, id: '5c24c8bb85d5b446aef2d47f' }
```

**Comment by adamreisnz** [comment] 2018-12-27 19:55
So it appears the solution would be to load your plugins prior to defining models. This seems like a logical thing to do, so I would probably recommend that in any case.

Will close this issue as there appears to be a suitable workaround in place.

**Closed as completed by adamreisnz** 2018-12-27 19:55 UTC

**Comment by georgiosd** [comment] 2019-12-19 09:56
@adamreisnz it's not directly apparent - I banged my head for 20-30 min before I found this issue. Would be great to mention this in the README
